version: '3.7'

services:
  postgres:
    image: postgres:12.1
    restart: always
    environment:
      POSTRGRES_USER: postgres
      POSTRGRES_PASSWORD: postgres
      POSTRGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-network
