version: '3.7'

services:
  postgres:
    image: postgres:12.1
    restart: always
    environment:
      POSTRGRES_USER: postgres
      POSTRGRES_PASSWORD: postgres
      POSTRGRES_DB: postgres
    ports:
      - 5433:5433
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
volumes:
  my_postgres_data:
